### ISSUE TITLE
有最新关于这方面的进展的Paper吗？我看Pensieve论文里说，没有多少改进空间了。

### ISSUE THREAD

**Issue by 945716994** [godka/Pensieve-PPO#20]
我是做因果强化学习的，对于这方面不太了解，所以想问问大佬有没有相关文章推荐一下。

**Comment by godka** [comment]
Sruthi, Panchapakesan C., Sanjay Rao, and Bruno Ribeiro. "Pitfalls of data-driven networking: A case study of latent causal confounders in video streaming." Proceedings of the Workshop on Network Meets AI & ML. 2020.
