### ISSUE TITLE
How is your baseline method implemented? 

### ISSUE THREAD

**Issue by 851682852** [godka/Pensieve-PPO#30]
I can see from your experimental results comparison chart that there are many algorithms, including BOLA, HYB, RB, etc. Can the implementation details of these algorithms be made public?
![image](https://github.com/godka/Pensieve-PPO/assets/59217335/1e4b8b50-66ab-49c0-a406-65cd492689f4)

**Comment by godka** [comment]
Hi,

Unfortunately, we can't provide implementations of other algorithms, as they fall outside the scope of this project's objectives. However, we welcome any form of improvement. Please feel free to pull requests.

Thank you,
Tianchi
