### ISSUE TITLE
a question about compute_v

### ISSUE THREAD

**Issue by linnaeushuang** [godka/Pensieve-PPO#4]
Hi,gaoka
thanks for your work.
but i'm confused by your calculation of Adv
https://github.com/godka/Pensieve-PPO/blob/f310bf19d6888d09864ee3d4fe46397ec667e2e0/src/ppo2.py#L150-L151

you let R_t=r_t+\gamma * R_{t+1}.
but in this loop,you use `reversed`.does that mean R_t=r_t+\gamma * R_{t-1}
is this a typo?
wait for your reply,thanks.

**Comment by godka** [comment]
Hi Linnaeus.
Good work for your Pensieve-PyTorch. It's pragmatic & impressive.
Regard to your question in terms of the advantage function, IMHO, you might have mistakenly mismatched the meaning of "reversed":

```
>>> list(reversed(range(3)))
[2, 1, 0]
```

To that end, the equation is somewhat equal to TD(1), aka MC. Note that such methods are consistent with the original Pensieve code.

One subtlety about that method is we tried lots of TD computation methodologies, e.g., TD(0) as well as GAE. However, they did not improve too much compared with the vanilla MC version.

https://github.com/godka/Pensieve-PPO/blob/fd77137b333c7114dd9ea6e251aa88bcb5db3189/src/ppo2.py#L151

Please feel free to let me know if you have other questions.

Tianchi.

**Comment by linnaeushuang** [comment]
wow,you're tianchi?
I like your work “comyco” very much. It inspires me a lot.I'm trying to do something base on "comyco".
thanks for your answer.I did make a mistake.

**Comment by godka** [comment]
Yep, I'm Tianchi. :)
It's nice to bump into you, Linnaeus.

**Comment by yangchaozhao** [comment]
> Hi Linnaeus.
> Good work for your Pensieve-PyTorch. It's pragmatic & impressive.
> Regard to your question in terms of the advantage function, IMHO, you might have mistakenly mismatched the meaning of "reversed":
> 
> ```
> >>> list(reversed(range(3)))
> [2, 1, 0]
> ```
> 
> To that end, the equation is somewhat equal to TD(1), aka MC. Note that such methods are consistent with the original Pensieve code.
> 
> One subtlety about that method is we tried lots of TD computation methodologies, e.g., TD(0) as well as GAE. However, they did not improve too much compared with the vanilla MC version.
> 
> https://github.com/godka/Pensieve-PPO/blob/fd77137b333c7114dd9ea6e251aa88bcb5db3189/src/ppo2.py#L151
> 
> Please feel free to let me know if you have other questions.
> 
> Tianchi.

Hi bro, I guess that TD(inf) is equal to  MC, aka GAE(1)，right? @godka

**Comment by godka** [comment]
Yep, it's TD(inf) @yangchaozhao. 
So sorry for the typo.

**Comment by EchoRickZz** [comment]
> > Hi Linnaeus.
> > Good work for your Pensieve-PyTorch. It's pragmatic & impressive.
> > Regard to your question in terms of the advantage function, IMHO, you might have mistakenly mismatched the meaning of "reversed":
> > ```
> > >>> list(reversed(range(3)))
> > [2, 1, 0]
> > ```
> > 
> > 
> > To that end, the equation is somewhat equal to TD(1), aka MC. Note that such methods are consistent with the original Pensieve code.
> > One subtlety about that method is we tried lots of TD computation methodologies, e.g., TD(0) as well as GAE. However, they did not improve too much compared with the vanilla MC version.
> > https://github.com/godka/Pensieve-PPO/blob/fd77137b333c7114dd9ea6e251aa88bcb5db3189/src/ppo2.py#L151
> > 
> > Please feel free to let me know if you have other questions.
> > Tianchi.
> 
> Hi bro, I guess that TD(inf) is equal to MC, aka GAE(1)，right? @godka

Hi bro, I guess you misunderstand td(lambda) with n-step boostrap. Actually, we don't say td(inf), since lambda here must be [0, 1] (otherwise it cannot converge), here is a simple (but clear) ref: https://blog.csdn.net/weixin_41362649/article/details/85028315, please check.

**Comment by yangchaozhao** [comment]
> > > Hi Linnaeus.
> > > Good work for your Pensieve-PyTorch. It's pragmatic & impressive.
> > > Regard to your question in terms of the advantage function, IMHO, you might have mistakenly mismatched the meaning of "reversed":
> > > ```
> > > >>> list(reversed(range(3)))
> > > [2, 1, 0]
> > > ```
> > > 
> > > 
> > > To that end, the equation is somewhat equal to TD(1), aka MC. Note that such methods are consistent with the original Pensieve code.
> > > One subtlety about that method is we tried lots of TD computation methodologies, e.g., TD(0) as well as GAE. However, they did not improve too much compared with the vanilla MC version.
> > > https://github.com/godka/Pensieve-PPO/blob/fd77137b333c7114dd9ea6e251aa88bcb5db3189/src/ppo2.py#L151
> > > 
> > > Please feel free to let me know if you have other questions.
> > > Tianchi.
> > 
> > 
> > Hi bro, I guess that TD(inf) is equal to MC, aka GAE(1)，right? @godka
> 
> Hi bro, I guess you misunderstand td(lambda) with n-step boostrap. Actually, we don't say td(inf), since lambda here must be [0, 1] (otherwise it cannot converge), here is a simple (but clear) ref: https://blog.csdn.net/weixin_41362649/article/details/85028315, please check.

I see, impressive comment! David‘s slides. TD(inf) refers to n-step temporal-difference in my subconscious, and I didn't realize that TD(x) means TD(lambda) more commonly, sorry for that and thanks for your correction .

**Comment by godka** [comment]
> > > > Hi Linnaeus.
> > > > Good work for your Pensieve-PyTorch. It's pragmatic & impressive.
> > > > Regard to your question in terms of the advantage function, IMHO, you might have mistakenly mismatched the meaning of "reversed":
> > > > ```
> > > > >>> list(reversed(range(3)))
> > > > [2, 1, 0]
> > > > ```
> > > > 
> > > > 
> > > > To that end, the equation is somewhat equal to TD(1), aka MC. Note that such methods are consistent with the original Pensieve code.
> > > > One subtlety about that method is we tried lots of TD computation methodologies, e.g., TD(0) as well as GAE. However, they did not improve too much compared with the vanilla MC version.
> > > > https://github.com/godka/Pensieve-PPO/blob/fd77137b333c7114dd9ea6e251aa88bcb5db3189/src/ppo2.py#L151
> > > > 
> > > > Please feel free to let me know if you have other questions.
> > > > Tianchi.
> > > 
> > > 
> > > Hi bro, I guess that TD(inf) is equal to MC, aka GAE(1)，right? @godka
> > 
> > 
> > Hi bro, I guess you misunderstand td(lambda) with n-step boostrap. Actually, we don't say td(inf), since lambda here must be [0, 1] (otherwise it cannot converge), here is a simple (but clear) ref: https://blog.csdn.net/weixin_41362649/article/details/85028315, please check.
> 
> I see, impressive comment! David‘s slides. TD(inf) refers to n-step temporal-difference in my subconscious, and I didn't realize that TD(x) means TD(lambda) more commonly, sorry for that and thanks for your correction . Sorry to tianchi old brother. @godka

@EchoRickZz Thanks to Ricky for your comments. It's my honor to be your faithful apprentice on general reinforcement learning, and, 
@yangchaozhao hh, I did make a mistake first. I've learned a lot from you.
