### ISSUE TITLE
 Is this project based on python3？and which version of tf2.x?

### ISSUE THREAD

**Issue by youngboy52** [godka/Pensieve-PPO#6]

**Comment by youngboy52** [comment]
Hi, I am new in this task and have some confusions of the prerequisite in your scripts. looking forward to your reply!

**Comment by youngboy52** [comment]
> No description provided.

**Comment by godka** [comment]
Hi Liang,
it's nice to meet you here.
Pensieve-PPO performs well on both python2 and python3,  as well as tensorflow >= 1.17.0.
For the PPO-only version please refer to this branch: https://github.com/godka/Pensieve-PPO/tree/ppo/src

Free free to let me know.

Best,
Tianchi

**Comment by youngboy52** [comment]
> Hi Liang,
> it's nice to meet you here.
> Pensieve-PPO performs well on both python2 and python3, as well as tensorflow >= 1.17.0.
> For the PPO-only version please refer to this branch: https://github.com/godka/Pensieve-PPO/tree/ppo/src
> 
> Free free to let me know.
> 
> Best,
> Tianchi

**Comment by youngboy52** [comment]
hi, thank you for your quick reply. I will try it with your suggestions.

**Comment by youngboy52** [comment]
> Hi Liang,
> it's nice to meet you here.
> Pensieve-PPO performs well on both python2 and python3, as well as tensorflow >= 1.17.0.
> For the PPO-only version please refer to this branch: https://github.com/godka/Pensieve-PPO/tree/ppo/src
> 
> Free free to let me know.
> 
> Best,
> Tianchi

Hi, Tianchi, sorry to disturb you again. My environment configs are python3.6 and tf2.4, but when I run train.py, there are lots of subprocess exist and it terminates due to 'out of cuda memory'. Could I take a look at your environment configs? In your scripts, there is no [setup.py](https://github.com/hongzimao/pensieve/blob/master/setup.py) as the original [pensive](https://github.com/hongzimao/pensieve), so I do not know the configs of mahimahi, apache, selenium and virtual display, could you show me the details of config before run train.py?  
Best, 
Liang
