### ISSUE TITLE
The time to train the model

### ISSUE THREAD

**Issue by SoonyangZhang** [godka/Pensieve-PPO#7]
Could you give me some hint on how long it takes to train the model with 1000000 epoch? Several days or weeks?With much thanks.

**Comment by godka** [comment]
Hi, 

You can press ctrl+c to terminate the process if you have observed that the validation curve has no longer increased on the tensorboard.
In common, the training process lasts less than 4 hours, almost 60k epochs.

Sorry for the typo, received on my phone.

Tianchi Huang
