### ISSUE TITLE
SAC import error

### ISSUE THREAD

**Issue by ahmad-hl** [godka/Pensieve-PPO#9]
In `train_sac.py` there is an import  `from sac import Network` which gives an error!

How did you install soft actor-critic (sac)?
Default installation using `pip install sac` leads to `Network` not found error!

**Comment by godka** [comment]
hi, sorry for the long delay.
The SAC version was implemented by @EchoRickZz . He will reply to you soon.

BTW, my SAC implementation can be found in https://github.com/godka/pensieve-sac

**Comment by EchoRickZz** [comment]
SAC is implemented by myself. Details are in the file  sac.py. Make sure you have downloaded all the files in **sac branch** https://github.com/godka/Pensieve-PPO/tree/SAC.
